### PR TITLE
allow to update variables manually

### LINKED ISSUE #16: allow for change variables value manually
sometimes I want to modify a variable's value manually instead of update it by sending requests.

### PR DESCRIPTION
**Pull request by sify21**
Try to resolve https://github.com/georgeflug/insomnia-plugin-save-variables/issues/16

### CODE REVIEW

**Comment by georgeflug** [comment]
I like this idea and appreciate the pull request. One thing that is a bit confusing to me is the "Custom Value" input box. If I was using this plugin for the first time, I would not know what it was for.

How about we remove the "Custom Value" input box and show a prompt when the user clicks the button? This would make it more clear what's happening and should simplify the implementation too. It could use a library such as [electron-prompt](https://www.npmjs.com/package/electron-prompt). The prompt could be pre-filled with the current value too which would be a nice touch.

**Comment by georgeflug** [comment]
Would you please run `npm run lint` and correct the style issues that are found?

**Comment by sify21** [comment]
Hi @georgeflug, I need some help, I don't know how to get `variableNameArg` in  `TemplateTag`'s `actions`. I only see that `variableNameArg` is passed as arguments of `TemplateTag`'s run method, so I added `Custom Value` in the args list, and passed `storeItemName` and `customValue` from `run` to `actions` through the context store. Is there another way to get `storeItemName`?

**Comment by sify21** [comment]
Oh I get it, just save `storeItemName` everytime ` TemplateTag`'s `run` is called. I updated the code to use  `electron-prompt`, please check again.

**Pull request merged**
